### ISSUE TITLE
Intial Developement for SDK

### ISSUE THREAD

**Issue by uwaheed88** [datopian/ckan3-py-sdk#1]
Intial setup for the package so, that we can make further developement on that.

## Tasks

* [x] Boot a repo: github.com/datopian/ckan3-py-sdk. **Done -- repo [here](https://github.com/datopian/ckan3-py-sdk)
* [x] Stub the README with e.g. what we have below **Done -- read [file](https://github.com/datopian/ckan3-py-sdk/blob/master/README.md)
* [x] Write a first failing test e.g. just the first part of upload which is authz request.
  * [x] Make it pass. **Done -- authz request test [commit link](https://github.com/datopian/ckan3-py-sdk/commit/b357915e805030a5694027732407a5ebeef963fe)
* [x] Do github actions so we have CI **Done -- actions .yml [file](https://github.com/datopian/ckan3-py-sdk/blob/master/.github/workflows/python-package.yml)
* [x] Start doing more tests **Done -- tests for authz and upload api [here](https://github.com/datopian/ckan3-py-sdk/blob/master/tests/test_uploader.py)

### Some other quick feedback:

* [x] If github actions done please add badge on front page
* [x] have you had  anyone else try this
* [x] do we have a python package (setup.py etc) so we can publish on pypi (later) - i imagine something like `ckan-client`
* [x] README seems a bit too focused just on versioning - i would frame this as a generic "CKAN 3 SDK for CKAN instances with CKAN v3 style cloud storage (see https://tech.datopian.com/blob-storage/)"
* [x] rename Tests section to Developers and add instructions on running the tests.
* [x] Is README up to date e.g. Instal section mentions setup.py but i don't see one ...
  * [x] Is getting started actually correct?

**Comment by uwaheed88** [comment]
@rufuspollock can you have a look, please.

**Comment by rufuspollock** [comment]
@uwaheed88 what should i look at exactly (there are no links to any code?)? And in general, can you have PRs so i can review ...

Regarding issue structure: task list looks very good 👍 👏  - on last item i'd like more detail e.g. tests of what (idea i think was that you would have completed the whole file upload flow).

Could you add acceptance and short description as per https://playbook.datopian.com/issues-tasks/#creating-issues

Also when updating tasks can you leave a comment as per https://playbook.datopian.com/issues-tasks/#completing-tasks

PS: do you want to assign yourself to the issue?

**Comment by rufuspollock** [comment]
Some other quick feedback:

* [ ] If github actions done please add badge on front page
* [ ] have you had  anyone else try this
* [ ] do we have a python package (setup.py etc) so we can publish on pypi (later) - i imagine something like `ckan-client`
* [ ] README seems a bit too focused just on versioning - i would frame this as a generic "CKAN 3 SDK for CKAN instances with CKAN v3 style cloud storage (see https://tech.datopian.com/blob-storage/)"
* [ ] rename Tests section to Developers and add instructions on running the tests.
* [ ] Is README up to date e.g. Instal section mentions setup.py but i don't see one ...
  * [ ] Is getting started actually correct?

**Comment by rufuspollock** [comment]
@uwaheed88 for me reviewing updates on issues, please

* copy checklist items back into description (e.g. from my comment) - i did not do this so my feedback was clear. Howeve ryou want those items in description so one place for all tasks
* update check list items as per https://playbook.datopian.com/issues-tasks/#completing-tasks - and if you are not clear on that please say. **specifically i expect a short bolded comment on a task explaining what you've done** so that i can do review really quickly.

As an illustration, you've checked:

> * [ ] If github actions done please add badge on front page

however, i can't see that badge on front page ...

![image](https://user-images.githubusercontent.com/180658/86490170-c9500580-bd66-11ea-9c95-a2850f0189a4.png)

Does that mean its in PR?? Not done, a confusion.

Also why is PyPI package failling?

**Comment by rufuspollock** [comment]
FIXED. All done - see also #6 (fixed).
