### ISSUE TITLE
[epic]

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan3-py-sdk#9]
Main work is to create a guide re metadata creation and automated metadata hinting / description/ validation.

When as a Python (or R) user I am creating datasets using Python (R) I want documentation and/or feedback as part of the SDK detailing how to programmatically reference/add the appropriate metadata fields, both mandatory and optional, and especially metadata fields that populate dropdowns so that I can quickly create a valid dataset

Terminology

* Profile: a spec for the metadata for a resource or dataset
* Schema: a spec for the fields of a resource

## Example

Example in R:

```
#Mandatory Fields

#lowercase alphanumeric and underscores only
name = 'sample_r_dataset2'

#display name
title = 'Sample R Dataset'

notes = 'Detailed Dataset Description'

maintainer='Dataset Maintainer Name'

maintainer_email='Dataset.Maintainer@xxx.org'

publisher='Dataset Publisher'

owner_org='yyy'

visibility='public'
# other options: 'private'

geographic_level='global'
#other options: 'national','regional','sub-national','other'

license_id='notspecified'

information_classification= 'public-public-external'
# other options: 'not_sensitive-non_confidential-internal-business', 'not_sensitive-non_confidential-internal-business', etc
```

## Acceptance

* [ ] Python SDK has a command to automatically describe the fields you should have and to output a yaml or json file you can fill in
* [ ] (?) There is an interactive command line tool for doing that ...
* [ ] Updated documentation for Python user guides with Package Create explanation and inclusion of metadata descriptions

## Tasks

* [ ] read about the json schemas for frictionless specs and read about json schema and json schema validators ...
